# @package algo
_target_: algo.dummy.DummyAgent
name: dummy
obs_type: ${suite.obs_type}
obs_shape: ??? # to be specified later
action_dim: ??? # to be specified later
device: ${device}
batch_size: 256
nstep: 3