# @package agent
_target_: agent.boosting.BoostingAgent
name: boosting
batch_size: ${algo.batch_size}
task: ${suite.task}
device: ${device}
feature_dim: ${feature_dim}
algo: ${algo}
representation: discriminator
disc_hidden_dim: 512
disc_type: ${disc_type}
disc_update_iter: ${disc_iter}
n_learners: ${n_learners}
