# @package agent
_target_: agent.ot.OTAgent
name: otil
task: ${suite.task}
device: ${device}
algo: ${algo}
expert_dir: /private/home/jdchang/state-il/expert_demos/
num_demos: 10
cost_fun: cosine
aggregator_fun: topk
solver_fun: sinkhorn
preprocessor_fun: noScaler
partial_updates: false
update_preprocessor_every_episode: 1
update_encoder_every_episode: 20
normalize: none
reward_scaling_fun: linear
reward_scaling_alpha: 1000.0
topk: 1
concatenate: false
fit_to_expert: false
reward_mode: offline_imitation
center_obs: false
load_encoder: true
use_trunk: true
rep_layer: enc
handcrafted: true
inv_reg: 1e-8
epsilon: 0.01
disc_type: s
